# Numpy Basics

In [2]:
import numpy as np

In [6]:
np.array(my_list) # convert list into a numpy array 

array([1, 2, 3])

In [7]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] #create an array

In [8]:
np.array(my_matrix) # convert list into numpy array, now with two dimensions

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**shift + tab on a method from a library to see his documentation**

In [9]:
np.arange(0, 10) # easy way to create an array, first parameter is a start, last, stop. *10 is not included.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 10, 2) # last parameter is the step. here, being two, output only evens

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(3) #c reate and fills an array with zeros

array([0., 0., 0.])

In [12]:
arr = np.zeros((5, 5)) # two dimensions array with zeros

In [13]:
arr #display

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((3,3)) # two dimensions array with ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.eye(4) # creates an identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
np.linspace(0, 10, 2) # little diferent from arange, first argument is the begin of your series, second, the end, 
# and third, how many numbers you wanna display equally spaced in this series

array([ 0., 10.])

In [18]:
np.linspace(0, 10, 5) # show me five numbers between 0 and 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
np.random.rand(5) # random is a sub library from numpy, rand is the method, you specify the number and by default he creates
# random numbers between 0 and 1

array([0.75063081, 0.394992  , 0.49225438, 0.01468621, 0.33732429])

In [20]:
np.random.rand(5) * 100 # between 0 and 100

array([66.11328971, 69.31207179,  8.18387452, 46.57160405, 86.69971574])

In [4]:
np.random.rand(5, 3) * 100 # 2 dimension array (matrix) with random numbers between 0 and 100

array([[33.53299041, 46.80381493, 57.87805466],
       [90.2288255 , 95.37573868, 32.10696847],
       [92.66282817, 88.13510986, 63.42835015],
       [92.08985374, 62.26767757, 50.81623907],
       [27.71364891, 20.87683714, 91.04795554]])

rand provides a uniform distribution

In [21]:
np.random.randn(4) # randn is no uniform like rand, its a Gausian distribution, its a normal distribution with mean 0 
# and standard deviation 1

array([ 0.73166931, -0.65142864,  0.79319564,  1.17609465])

In [22]:
np.random.randint(0, 100, 10) # integers numbers

array([63, 43, 32, 52, 62,  9, 72, 18, 11, 94])

In [23]:
np.round(np.random.rand(5)*100, 0) # equivalent to randint

array([46., 18.,  6., 29., 25.])

In [25]:
arr = np.random.rand(25) #creates a distribution

In [26]:
arr #displays the vector of size 25 created above

array([0.3909563 , 0.29975066, 0.15145071, 0.80572827, 0.54127176,
       0.84351108, 0.26783506, 0.31962552, 0.32875482, 0.85883516,
       0.61634205, 0.72677577, 0.12639901, 0.71533585, 0.61062319,
       0.42370689, 0.10354125, 0.08175581, 0.83987386, 0.15264339,
       0.6050265 , 0.71778087, 0.10885749, 0.18141459, 0.21056806])

In [27]:
arr.reshape((5,5)) # reshapes the distribution to become a matrix and displays (he do not assign this values to arr)

array([[0.3909563 , 0.29975066, 0.15145071, 0.80572827, 0.54127176],
       [0.84351108, 0.26783506, 0.31962552, 0.32875482, 0.85883516],
       [0.61634205, 0.72677577, 0.12639901, 0.71533585, 0.61062319],
       [0.42370689, 0.10354125, 0.08175581, 0.83987386, 0.15264339],
       [0.6050265 , 0.71778087, 0.10885749, 0.18141459, 0.21056806]])

In [28]:
arr.shape # gonna display that still is a size 25 vector

(25,)

In [29]:
arr = arr.reshape((5,5)) # now assigning the reshape

In [30]:
arr.shape # display that becomes a matrix

(5, 5)

In [37]:
arr.max() #max value
arr.min() #min value
arr.argmax() #max value position
arr.argmin() #min value position

17