# Numpy Operations 
- Aritmetics operations between arrays
- Operations between scalar arrays
- Some pre programmed functions of numpy

In [1]:
import numpy as np

In [4]:
arr = np.arange(0,16)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [8]:
arr + arr # add arrays *should be the same size
arr - arr
arr * arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [9]:
arr / arr #if your divide by 0 the code stops and output only an error, numpy output only an warning and display "nan"

/home/leopoldo/.local/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

In [10]:
1 / arr # return inf

/home/leopoldo/.local/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667])

In [ ]:
arr + 100 # add the number on all elements
arr - 100
arr ** 10
arr * 100
arr / 100 

In [ ]:
np.sqrt(arr) # return square root of each elements
np.exp(arr) # return exponencial of each elements
np.mean(arr) # return the mean of all elements
np.std(arr) # return the standard deviation of all elements
np.sin(arr) # return the sine of each element

**Numpy universal functions can be found in:** <br>
https://docs.scipy.org/doc/numpy/reference/ufuncs.html